use super::*;

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum EnchantType {
    AbsorbHealth,
    AbsorbMagicka,
    AbsorbStamina,
    BefouledWeapon,
    Berserker,
    ChargedWeapon,
    DamageHealth,
    DamageShield,
    DecreasePhysicalDamage,
    DecreaseSpellDamage,
    DiseaseResistant,
    FieryWeapon,
    FireResistant,
    FrostResistant,
    FrozenWeapon,
    Health,
    HealthRegen,
    IncreaseBashDamage,
    IncreasePhysicalDamage,
    IncreasePotionEffectiveness,
    IncreaseSpellDamage,
    Invalid,
    Magicka,
    MagickaRegen,
    None,
    PoisonedWeapon,
    PoisonResistant,
    PrismaticDefense,
    PrismaticOnslaught,
    PrismaticRegen,
    ReduceArmor,
    ReduceBlockAndBash,
    ReduceFeatCost,
    ReducePotionCooldown,
    ReducePower,
    ReduceSpellCost,
    ShockResistant,
    Stamina,
    StaminaRegen,
}
